appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: J9U1p3uQK61qECBGosTjLh1Wmo0AxcX5e6FHLYGQwwEdkwZs35u8wxpsgWo4Vqvu553YLlYEhG+B46SdNooKqYnMtrSYKsiapW3ht8oPumc6XkdSSxb1uDq79HDcujRnSom4rhqZcwABrvl+7JcsxKIhn55lyAfC8XDmCNBVgMYAaIbeOrMLcmE6r6u3cQUOHrRK+49gYZDeb5Dtk1RlUVQG9ni9YAj7RLSthnGNyrmtGvoxy+xMAZKh9nyUMqVIU156NqTrcj//MVMOBHFClP144JXTm1RXJFE5GOVZDaTYPYW7mfPh7NGlbCMU4QMt3na9sIJGNUGbCpXPnBNecmTAcbjtA8PczARxBMsWktyBztgkmeWUOye9s8rBD1kctVujUZGCMM3I9XsPZP/RQl6dg0nmgPxo5dNYRdFhWs0wCGsA/kJdOKuy2PbbFiN2iz6nabZzLzhAfxsE3Sk4FIzBoBHtR0tca/szEqWMRFfb91iQqC8SnVP5ViPqG20ILF2czW+5ARm/1ZkdeLAEAk6TjzNSMCyuoL+UA+no2KTaH7ZttxSARH34vzt1JAyJNRKr/fj9G+40cN5D1WPe8HHQ8xnmWl0uVQjlHOqEJhzkI4tGo3dPiK8MYEIwRMXq6m7sk73pSIbQYpH9EC/sNSk/6zOL09859jTf1YytaXk=}
conda_forge_output_validation: true
