travis:
  secure:
    BINSTAR_TOKEN: jnc+lgSlEg/OBvzpah5gEcN+ok3aL4lG7FZ/MjYuPH5HFxxCORXFl7iZv+hUrR0I7EL//acor/sGTYk390mMdGNV6Es5qGmAXPAkbOGIiQyVsCTjObhOC4T4cIVJJuP2jmjMJXRqDM3V++ki9AbLfmjuyZm7hf4Igf/M2A717TjNcSVcZppfVbDJbDvZUC0lK7Rk9fFaQ3hyI+bQbFw70v7l0T6PFKLk8kva2QCALhOJ7BCNpx18AkeqQy0ryheGzhcQTURlkEZmK9sIzCEBSyAGirQlH6097gAlvjx717Fq10SdGaRnv4m9tXAMI5eS7Ds9B0jGyybH7Er2kt/xS8pP/Ej/PfY9k7oBgZODM72Z3kJkfLOi5mKE6Mv3SixSUE2Nm8j6F3lcnyK7a4I3xIbnYXK2GGnIB/83a6WE2V4PGGLPknBCz6FdWhSx9CRh7gLufSG9FGnAZUb9I8b05qcR34wQS0K94/TVVb3kDxv7EwQHm6lOl1V46w1ygTkM7JCQ5kghcZLLGZzLQkL5Dimt+gOj3wtahLjZe3yItxhLgjX6mlQraJ/xJIecIbM3kaojah0iHMtgPXiRcuoQsHi4L7FeXEsk6dJUz7y3SL92FyqMiD3KwA/uPNib6mEJ07e9XYzhZtoCv+3vddeNgjZ4csA3vMgRt72nxKeUoUs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
